project:
  type: book
  output-dir: docs

book:
  title: "Guide pour la description d'une expérimentation en vigne"
  original-date: 2023-02-15	
  date: 2023-09-05
  author: 
  - name: Xavier Delpuech
    corresponding: true
    orcid: 0000-0001-7278-3209
    email: xavier.delpuech@vignevin.com
    affiliations:
      - IFV
  - name: Vincent Dumas
    affiliations:
      - INRAE
  - name: Jean-Yves Cahurel
    affiliations:
      - IFV
  - name: Laure Gontier
    affiliations:
      - IFV
  - name: Marion Claverie
    affiliations:
      - IFV
  - name: Arnaud Charleroy
    affiliations:
      - INRAE
  - name: Viviane Bécart
    affiliations:
      - SGVRCDR
  - name: Romain Lacroix
    affiliations:
      - SGVRCDR
  - name: Eric Duchêne
    affiliations:
      - INRAE
  - name: Nathalie Ollat
    affiliations:
      - INRAE
  - name: Joseph Tran
    affiliations:
      - INRAE
  - name: Catherine Roussey
    orcid: 0000-0002-3076-5499
    affiliations:
      - INRAE
  chapters:
    - index.qmd
    - intro.qmd
    - general_context.qmd
    - expe_design.qmd
    - vineyard_context.qmd
    - data.qmd
    - references.qmd
    - about.qmd
  appendices:
    - glossary.qmd
    - schema_xp.qmd
    - soilManagementCode.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt

editor: visual
lang: fr

